### ISSUE TITLE
npm run build 报错

### ISSUE THREAD

**Issue by gitfornncn** [lincenying/mmf-blog-react-v2#2]
您好！打扰了,尝试npm run build 出现以下报错

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.11.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.6.0
3 info using node@v9.11.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle mmf-blog-react-v2@1.0.0~prebuild: mmf-blog-react-v2@1.0.0
6 info lifecycle mmf-blog-react-v2@1.0.0~build: mmf-blog-react-v2@1.0.0
7 verbose lifecycle mmf-blog-react-v2@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle mmf-blog-react-v2@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/www/blog/node_modules/.bin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle mmf-blog-react-v2@1.0.0~build: CWD: /www/blog
10 silly lifecycle mmf-blog-react-v2@1.0.0~build: Args: [ '-c', 'node build/build.js --debug-template' ]
11 silly lifecycle mmf-blog-react-v2@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle mmf-blog-react-v2@1.0.0~build: Failed to exec build script
13 verbose stack Error: mmf-blog-react-v2@1.0.0 build: `node build/build.js --debug-template`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid mmf-blog-react-v2@1.0.0
15 verbose cwd /www/blog
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/Cellar/node/9.11.1/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v9.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error mmf-blog-react-v2@1.0.0 build: `node build/build.js --debug-template`
22 error Exit status 1
23 error Failed at the mmf-blog-react-v2@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lincenying** [comment]
webpack4的插件不兼容, 已修复
git pull 下, 然后重新yarn后npm run build即可

**Comment by gitfornncn** [comment]
感谢！
